codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false
comment:
  require_changes: true
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
