name: Pre-commit auto-update

on:
  # every day at midnight
  schedule:
    - cron: "0 0 * * *"
  # on demand  
  workflow_dispatch:

jobs:
  auto-update:
    environment: precommit-autoupdate
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Checkout repo
        uses: actions/checkout@v2.4.0
      
      - name: Setup Python
        uses: actions/setup-python@v2
      
      - name: Install pre-commit
        run: python -m pip install pre-commit
        
      - name: Run pre-commit autoupdate
        run: pre-commit autoupdate
      
      - name: Create a Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
          branch: update/pre-commit-hooks
          title: Update pre-commit hooks
          commit-message: "MAINT: update pre-commit hooks"
          body: Update versions of pre-commit hooks to latest version.
